In [1]:
import numpy as np
import lsequbo

In [2]:
A = np.array([[1, 0, 0], [-1, 2, -1], [0, 0, 1]])
b = np.array([0, 0, 2])

In [3]:
A

array([[ 1,  0,  0],
       [-1,  2, -1],
       [ 0,  0,  1]])

In [4]:
lse = lsequbo.LSE(A=A, b=b)

In [5]:
lse.info

{'real': np.True_,
 'solution': array([0., 1., 2.]),
 'min(x)': np.float64(0.0),
 'max(x)': np.float64(2.0),
 'fractional_part': np.float64(0.0),
 'square': True,
 'symmetric': False,
 'spectrum': array([2., 1., 1.]),
 'positive_semi-definite': np.True_,
 'positive_definite': np.True_,
 'determinant': np.float64(2.0),
 'hamming matrix': array([[1, 0, 0],
        [1, 1, 1],
        [0, 0, 1]]),
 'hamming weight': np.int64(5)}

In [6]:
lse.x

array([0., 1., 2.])

In [7]:
np.bitwise_count(np.array([0, 1, 2]))

array([0, 1, 1], dtype=uint8)

In [8]:
np.bitwise_count([0, 0, 1, 1, 0, 1, 0, 1, 1])

array([0, 0, 1, 1, 0, 1, 0, 1, 1], dtype=uint8)